spring:
  application.name: Spring_Boot_Chat_Application
  datasource:
    url: jdbc:postgresql://localhost:5432/ChatApplication
    password: postgres
    username: postgres
logging:
  level:
    web: debug
server.error.include-stacktrace: never